name: Run Unit Tests and Lint
defaults:
  run:
    working-directory: subfolders
jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
              npm ci
              npm run test
