name: Run Unit Tests and Lint
on : pull_request
jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: subfloders
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
          cache-dependency-path: subfloders/package-lock.json

      - name: Install
        run: npm ci

      # - run: ls
      # - run: pwd
      - name: Running Tests
        run: npm run test
