name: Run Unit Tests and Lint
on : pull_request
jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./subfolders
    steps:
      - uses: actions/checkout@v2
      - run: |
              npm ci
              npm run test
