name: Run Unit Tests and Lint
on : 
  pull_request:
    paths:
      - 'subfloders/**'
  push:
    branches:
      - main
defaults:
  run:
    working-directory: subfloders
jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
          cache-dependency-path: subfloders/package-lock.json

      - name: Install
        run: npm ci

      # - run: ls
      # - run: pwd
      - name: Running Tests
        run: npm run test
