name: Run Unit Tests and Lint
on : pull_request
jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - run: pwd
      - run: cd ./subfloders
      - run: npm install
      - run: npm run test
