name: Run Unit Tests and Lint
env:
  APP_PATH: subfloders
on : 
  pull_request:
    paths:
      - "${{env.APP_PATH}}/**"
  push:
    paths:
      - "${{env.APP_PATH}}/**"
    branches:
      - main
defaults:
  run:
    working-directory: ${{env.APP_PATH}}
jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
          cache-dependency-path: ${{env.APP_PATH}}/package-lock.json

      - name: Install
        run: npm ci

      - name: Running Tests
        run: npm run test
